### ISSUE TITLE
PR 取り込み後、v2.0.0 に上げる

### ISSUE THREAD

**Issue by naotawool** [naotawool/salary-calculation#34]
#32 の PR を develop に取り込み後、アプリバージョンを 2.0.0 にメジャーバージョンアップする。

**Comment by naotawool** [comment]
あと、その前にビルドシステムを maven (pom.xml) から gradle (build.gradle) に変更すること。

**Comment by miya-masa** [comment]
PR #36 で作りなおしました。お願いしますー。

**Comment by naotawool** [comment]
#36 merge done!!

**Comment by naotawool** [comment]
残タスク
- #33
- ビルドシステムを maven --> gradle
- #36 取り込み後のリファクタリング

**Comment by naotawool** [comment]
> ビルドシステムを maven --> gradle

DONE!!

**Comment by naotawool** [comment]
#33 done
